//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kategori
    {
        public Kategori()
        {
            this.Program = new HashSet<Program>();
            this.Program1 = new HashSet<Program>();
            this.Program2 = new HashSet<Program>();
            this.Program3 = new HashSet<Program>();
            this.Program4 = new HashSet<Program>();
            this.Program5 = new HashSet<Program>();
        }
    
        public int KategoriId { get; set; }
        public string KategoriAdi { get; set; }
        public int KategoriKapasite { get; set; }
    
        public virtual ICollection<Program> Program { get; set; }
        public virtual ICollection<Program> Program1 { get; set; }
        public virtual ICollection<Program> Program2 { get; set; }
        public virtual ICollection<Program> Program3 { get; set; }
        public virtual ICollection<Program> Program4 { get; set; }
        public virtual ICollection<Program> Program5 { get; set; }
    }
}
