//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class KisiBilgileri
    {
        public int ID { get; set; }
        public string TC { get; set; }
        public System.DateTime Tarih { get; set; }
        public int Kilo { get; set; }
        public int Boy { get; set; }
        public int Kalori { get; set; }
        public int Kosu { get; set; }
        public int CalismaSaati { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
    }
}
