//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public Kullanici()
        {
            this.KisiBilgileri = new HashSet<KisiBilgileri>();
            this.Rezervasyon = new HashSet<Rezervasyon>();
        }
    
        public string TC { get; set; }
        public string Sifre { get; set; }
        public string Adi { get; set; }
        public string Soyadi { get; set; }
        public Nullable<System.DateTime> Yas { get; set; }
    
        public virtual ICollection<KisiBilgileri> KisiBilgileri { get; set; }
        public virtual ICollection<Rezervasyon> Rezervasyon { get; set; }
    }
}
