//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Software
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class SoftwareSporSalonuEntities : DbContext
    {
        public SoftwareSporSalonuEntities()
            : base("name=SoftwareSporSalonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admin { get; set; }
        public DbSet<Kategori> Kategori { get; set; }
        public DbSet<KisiBilgileri> KisiBilgileri { get; set; }
        public DbSet<Kullanici> Kullanici { get; set; }
        public DbSet<Program> Program { get; set; }
        public DbSet<Rezervasyon> Rezervasyon { get; set; }
    
        public virtual int RezervasyonYap(Nullable<System.DateTime> tarih, string tc, Nullable<System.DateTime> reztarih)
        {
            var tarihParameter = tarih.HasValue ?
                new ObjectParameter("tarih", tarih) :
                new ObjectParameter("tarih", typeof(System.DateTime));
    
            var tcParameter = tc != null ?
                new ObjectParameter("tc", tc) :
                new ObjectParameter("tc", typeof(string));
    
            var reztarihParameter = reztarih.HasValue ?
                new ObjectParameter("reztarih", reztarih) :
                new ObjectParameter("reztarih", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("RezervasyonYap", tarihParameter, tcParameter, reztarihParameter);
        }
    }
}
